var  appList = ''

appList += '<a href="https://bit.ly/36r3dR6" data-app-id="animal" class="list-group-item list-group-item-action">미래 남편의 동물관상</a>'
appList += '<a href="https://bit.ly/3fezONQ" data-app-id="idle" class="list-group-item list-group-item-action">아이들 테스트</a>'
appList += '<a href="https://bit.ly/35hDZnz" data-app-id="nct" class="list-group-item list-group-item-action">NCT 테스트</a>'
appList += '<a href="https://bit.ly/2SiRoXp" data-app-id="twice" class="list-group-item list-group-item-action">트와이스 테스트</a>'
appList += '<a href="https://bit.ly/2Sj4zau" data-app-id="seventeen" class="list-group-item list-group-item-action">세븐틴 테스트</a>'
appList += '<a href="https://bit.ly/35h4I3w" data-app-id="vixx" class="list-group-item list-group-item-action">VIXX 테스트</a>'
appList += '<a href="https://bit.ly/2yWdO9O" data-app-id="cosmicgirls" class="list-group-item list-group-item-action">우주소녀 테스트</a>'
appList += '<a href="https://bit.ly/2zKoiK9" data-app-id="exo" class="list-group-item list-group-item-action">EXO 테스트</a>'
appList += '<a href="https://bit.ly/2Yooets" data-app-id="redvelvet" class="list-group-item list-group-item-action">레드벨벳 테스트</a>'
appList += '<a href="https://bit.ly/3cXoPqg" data-app-id="april" class="list-group-item list-group-item-action">에이프릴 테스트</a>'
appList += '<a href="https://bit.ly/2SjchSd" data-app-id="b1a4" class="list-group-item list-group-item-action">B1A4 테스트</a>'
appList += '<a href="https://bit.ly/2yVVEFa" data-app-id="bts" class="list-group-item list-group-item-action">BTS 테스트</a>'
appList += '<a href="https://bit.ly/2xbvz4E" data-app-id="president" class="list-group-item list-group-item-action">대통령 테스트</a>'